# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "generic/ubuntu2004"
    config.vm.hostname = "slack-service"
    config.vm.synced_folder "./../..", "/vagrant", type: "nfs"
    config.vm.provision :shell, path: "./../provision.sh"
    config.vm.network "forwarded_port", guest: 4311, host: 4311
    config.vm.network "forwarded_port", guest: 4312, host: 4312

    config.vm.provider :libvirt do |v|
        v.default_prefix = "slack-service"
    end

  end
  